# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "hashicorp/precise64"
  if ENV['AMBER_PUBLIC_KEY_DIR']
    config.vm.synced_folder ENV['AMBER_PUBLIC_KEY_DIR'], "/vagrant_public_keys"    
  end

  config.vm.provision "shell", path: "setup.sh", args: ENV['RELEASE_TAG']
  config.vm.network "forwarded_port", guest: 80, host: 9000, auto_correct: true 

  config.vm.provider "aws" do |aws, override|
    config.vm.box = "dummy"
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME']

    aws.ami = "ami-018c9568"
    aws.instance_type = "t1.micro"

    aws.tags = { 'Name' => 'Amber nginx: ' + (ENV['RELEASE_TAG'] ? ENV['RELEASE_TAG'] : 'master') }
    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = ENV['AWS_PRIVATE_AWS_SSH_KEY_PATH']
  end

end
